/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoProveedores;
import modelo.Proveedor;

/**
 *
 * @author Geovanny
 */
public class FRM_MantenimientoProveedores extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoProveedores
     */
    Controlador_FRM_MantenimientoProveedores controlador;
    public FRM_MantenimientoProveedores() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new Controlador_FRM_MantenimientoProveedores();
        jP_Botones1.agregarEventosProveedores(controlador);
    } 
    
    public String obtenerCedula(){
       return jP_InformacionProveedor1.obtenerCedula();
    }
    
    public void mostrarInformacion(Proveedor proveedor)
    {
        jP_InformacionProveedor1.mostrarInformacion(proveedor);
    }
    
    public void habilitarModificarEliminar()
    {
        jP_Botones1.habilitarModificarEliminar();
    }
    
    public void habilitarAgregar(){
        jP_InformacionProveedor1.habilitarAgregar();
        jP_Botones1.habilitarAgregar();
    }
    
    public void limpiarVentana()
    {
        jP_InformacionProveedor1.limpiarVentana();
    }
    
    public Proveedor getProveedor()
    {
        return jP_InformacionProveedor1.getProveedor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_InformacionProveedor1 = new vista.JP_InformacionProveedor();
        jP_Botones1 = new vista.JP_Botones();

        setTitle("Registro de Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_InformacionProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_InformacionProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.JP_Botones jP_Botones1;
    private vista.JP_InformacionProveedor jP_InformacionProveedor1;
    // End of variables declaration//GEN-END:variables
}
