/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Clientes;
import modelo.Cliente;
import modelo.ConexionBD;

/**
 *
 * @author Jose Rodolfo
 */
public class FRM_MantenimientoClientes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoClientes
     */
    Controlador_FRM_Clientes controlador;
    
    public FRM_MantenimientoClientes(ConexionBD conexion) {
        //setUndecorated(true);     Para quitar bordes de ventana en netbeans
        initComponents();
        setLocationRelativeTo(null);
        controlador = new Controlador_FRM_Clientes(conexion, this);
        jP_Botones1.agregarEventosClientes(controlador);
        btn_Reporte.addActionListener(controlador);
    }//Fin del constructor
    
    public void limpiarVentana(){
        jP_InformacionClientes1.limpiarVentana();
        jP_Botones1.estadoInicial();
    }//Fin del metodo limpiarVentana
    
    public String obtenerCedula(){
        return jP_InformacionClientes1.obtenerCedula();
    }//Fin del metodo obtenerCedula
    
    public void mostrarInformacionCliente(Cliente cliente){
        jP_InformacionClientes1.mostrarInformacionCliente(cliente);
    }//Fin del metodo
    
    public void habilitarModificarEliminar(){
        jP_Botones1.habilitarModificarEliminar();
    }//Fin del metodo
    
    public void habilitarAgregar(){
        jP_InformacionClientes1.habilitarAgregar();
        jP_Botones1.habilitarAgregar();
    }//Fin del metodo 
    
    public Cliente getCliente(){
        return jP_InformacionClientes1.getCliente();
    }//Fin del metodo getCliente    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Registro Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}//Fin de la clase
