/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoProveedores;
import modelo.ConexionBD;
import modelo.Proveedor;

/**
 *
 * @author Geovanny
 */
public class FRM_MantenimientoProveedores extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoProveedores
     */
    Controlador_FRM_MantenimientoProveedores controlador;
    public FRM_MantenimientoProveedores(ConexionBD conexion) {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new Controlador_FRM_MantenimientoProveedores(conexion,this);
        jP_Botones1.agregarEventosProveedores(controlador);
    } 
    
    public String obtenerCedula(){
       return jP_InformacionProveedor2.obtenerCedula();
    }
    
    public void mostrarInformacion(Proveedor proveedor)
    {
        jP_InformacionProveedor2.mostrarInformacion(proveedor);
    }
    
    public void habilitarModificarEliminar()
    {
        jP_Botones1.habilitarModificarEliminar();
    }
    
    public void habilitarAgregar(){
        jP_InformacionProveedor2.habilitarAgregar();
        jP_Botones1.habilitarAgregar();
    }
    
    public void limpiarVentana()
    {
        jP_InformacionProveedor2.limpiarVentana();
    }
    
    public Proveedor getProveedor()
    {
        return jP_InformacionProveedor2.getProveedor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Botones1 = new vista.JP_Botones();
        jP_InformacionProveedor2 = new vista.JP_InformacionProveedor();

        setTitle("Registro de Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_InformacionProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_InformacionProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.JP_Botones jP_Botones1;
    private vista.JP_InformacionProveedor jP_InformacionProveedor2;
    // End of variables declaration//GEN-END:variables
}
