/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Proveedor;

/**
 *
 * @author Geovanny
 */
public class JP_InformacionProveedor extends javax.swing.JPanel {

    /**
     * Creates new form JP_InformacionProveedor
     */
    public JP_InformacionProveedor() {
        initComponents();
    } 
    
    public String obtenerCedula()
    {
        return jt_Cedula.getText();
    }
    
    public void limpiarVentana()
    {
        jt_Cedula.setText("");
        jt_NombreEmpresa.setText("");
        jt_Direccion.setText("");
        jt_Productos.setText("");
        
        jt_Cedula.setEnabled(true);
        jt_NombreEmpresa.setEnabled(false);
        jt_Direccion.setEnabled(false);
        jt_Productos.setEnabled(false);
        
    }
    
    public void mostrarInformacion(Proveedor proveedor)
    {
        jt_Cedula.setText(proveedor.getCedula());
        jt_NombreEmpresa.setText(proveedor.getNombreEmpresa());
        jt_Direccion.setText(proveedor.getDireecion());
        jt_Productos.setText(proveedor.getProductos());
    } 
    
    public void habilitarAgregar()
    {
        jt_Cedula.setEnabled(false);
        jt_NombreEmpresa.setEnabled(true);
        jt_Direccion.setEnabled(true);
        jt_Productos.setEnabled(true);
    }
    
    public Proveedor getProveedor()
    {
        Proveedor proveedor= new Proveedor(jt_Cedula.getText(), jt_NombreEmpresa.getText(),jt_Direccion.getText(),jt_Productos.getText());
        return proveedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreEmpresa = new javax.swing.JTextField();
        jl_DireccionP = new javax.swing.JLabel();
        jt_Direccion = new javax.swing.JTextField();
        jl_Productos = new javax.swing.JLabel();
        jt_Productos = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jl_Cedula.setText("Cedula:");

        jl_Nombre.setText("Nombre de la Empresa:");

        jt_NombreEmpresa.setEnabled(false);

        jl_DireccionP.setText("Dirección:");

        jt_Direccion.setEnabled(false);

        jl_Productos.setText("Productos:");

        jt_Productos.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Nombre)
                    .addComponent(jl_Cedula)
                    .addComponent(jl_DireccionP)
                    .addComponent(jl_Productos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_NombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jt_Cedula)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Cedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_DireccionP)
                    .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Productos)
                    .addComponent(jt_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_DireccionP;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Productos;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_NombreEmpresa;
    private javax.swing.JTextField jt_Productos;
    // End of variables declaration//GEN-END:variables
}
