/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Cliente;

/**
 *
 * @author Jose Rodolfo
 */
public class JP_InformacionClientes extends javax.swing.JPanel {

    /**
     * Creates new form JP_InformacionClientes
     */
    public JP_InformacionClientes() {
        initComponents();
        buttonGroup1.add(rb_Femenino);
        buttonGroup1.add(rb_Masculino);
        jcb_Dia.removeAllItems();
        jcb_Mes.removeAllItems();
        jcb_Anio.removeAllItems();
        llenarDia();
        llenarMes();
        llenarAnio();
        jcb_Anio.setSelectedItem("1990");
    }//Fin del constructor
    
    public void mostrarInformacionCliente(Cliente cliente){
        jt_NombreCompleto.setText(cliente.getCedula());
        jt_Cedula.setText(cliente.getNombreCompleto());
        
        if(cliente.getGenero() == ('F'))
            rb_Masculino.setSelected(true);
        else
            rb_Femenino.setSelected(true);
        
        //jcb_Dia.setSelectedItem(cliente.getFechaNacimiento());
        //jcb_Mes.setSelectedItem(cliente.getFechaNacimiento());
        //jcb_Anio.setSelectedItem(cliente.getFechaNacimiento());
        
        jt_TelefonoA.setText(cliente.getNumeroTelefono()[0]);
        jt_TelefonoB.setText(cliente.getNumeroTelefono()[1]);
        jt_CorreoElectronico.setText(cliente.getCorreoElectronico());
        jta_Direccion.setText(cliente.getDireccion());
    }//Fin del metodo mostrarInformacionCliente
    
    public void habilitarAgregar(){
        jt_Cedula.setEnabled(false);
        jt_NombreCompleto.setEnabled(true);
        rb_Masculino.setEnabled(true);
        rb_Femenino.setEnabled(true);
        jcb_Dia.setEnabled(true);
        jcb_Mes.setEnabled(true);
        jcb_Anio.setEnabled(true);
        jt_TelefonoA.setEnabled(true);
        jt_TelefonoB.setEnabled(true);
        jt_CorreoElectronico.setEnabled(true);
        jta_Direccion.setEnabled(true);
    }//Fin del metodo
    
    public String obtenerCedula(){
        return jt_NombreCompleto.getText();
    }//Fin del metodo obtenerCedula
    
    public void llenarDia(){
        for(int i=1; i<32; i++){
            jcb_Dia.addItem(""+i);
        }//Fin del for
    }//Fin del método llenarDia
    
    public void llenarMes(){
        for(int i=1; i<13; i++){
            jcb_Mes.addItem(""+i);
        }//Fin del for
    }//Fin del método llenarMes
    
    public void llenarAnio(){
        for(int i=1940; i<2020; i++){
            jcb_Anio.addItem(""+i);
        }//Fin del for
    }//Fin del método llenarMes

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jl_Cedula = new javax.swing.JLabel();
        jl_NombreCompleto = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jl_FechaNacimiento = new javax.swing.JLabel();
        jl_Dia = new javax.swing.JLabel();
        jcb_Dia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcb_Mes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcb_Anio = new javax.swing.JComboBox<>();
        jl_Telefonos = new javax.swing.JLabel();
        jt_TelefonoA = new javax.swing.JTextField();
        jt_TelefonoB = new javax.swing.JTextField();
        jl_CorreoElectronico = new javax.swing.JLabel();
        jt_CorreoElectronico = new javax.swing.JTextField();
        jl_Direccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Direccion = new javax.swing.JTextArea();

        jl_Cedula.setText("Cédula:");

        jl_NombreCompleto.setText("Nombre Completo:");

        jt_NombreCompleto.setEnabled(false);

        jLabel1.setText("Género: ");

        rb_Masculino.setText("Masculino");
        rb_Masculino.setEnabled(false);

        rb_Femenino.setText("Femenino");
        rb_Femenino.setEnabled(false);

        jl_FechaNacimiento.setText("Fecha Nacimiento:");

        jl_Dia.setText("Día:");

        jcb_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_Dia.setEnabled(false);

        jLabel2.setText("Mes: ");

        jcb_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_Mes.setEnabled(false);

        jLabel3.setText("Año:");

        jcb_Anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_Anio.setEnabled(false);

        jl_Telefonos.setText("Números de Teléfonos: ");

        jt_TelefonoA.setEnabled(false);

        jt_TelefonoB.setEnabled(false);

        jl_CorreoElectronico.setText("Correo Electrónico: ");

        jt_CorreoElectronico.setEnabled(false);

        jl_Direccion.setText("Dirección:");

        jta_Direccion.setColumns(20);
        jta_Direccion.setRows(5);
        jta_Direccion.setText("\n");
        jta_Direccion.setEnabled(false);
        jScrollPane1.setViewportView(jta_Direccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jl_FechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_Cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_NombreCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_Masculino)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Femenino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_Dia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jt_Cedula)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_Telefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_CorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jt_CorreoElectronico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jt_TelefonoA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jt_TelefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jl_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_Masculino)
                    .addComponent(rb_Femenino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_TelefonoB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jl_Telefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jt_TelefonoA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_CorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jt_CorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_Anio;
    private javax.swing.JComboBox<String> jcb_Dia;
    private javax.swing.JComboBox<String> jcb_Mes;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_CorreoElectronico;
    private javax.swing.JLabel jl_Dia;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_FechaNacimiento;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JLabel jl_Telefonos;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_CorreoElectronico;
    private javax.swing.JTextField jt_NombreCompleto;
    private javax.swing.JTextField jt_TelefonoA;
    private javax.swing.JTextField jt_TelefonoB;
    private javax.swing.JTextArea jta_Direccion;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    // End of variables declaration//GEN-END:variables
}
